/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ModelSelect: typeof import('./src/components/ModelSelect.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    PullModelDialog: typeof import('./src/components/PullModelDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
