version: '3'

services:
  bolter-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: bolter-ui:latest
    container_name: bolter-ui
    ports:
      - '8080:80'
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    networks:
      - ollama-network
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - '11434:11434'
    networks:
      - ollama-network
    restart: unless-stopped

networks:
  ollama-network:
    driver: bridge

volumes:
  ollama-data:
    driver: local
